# Trying to reproduce the results of _Beyond the English web: ..._

Finnish monolingual example:

In [1]:
from sklearn.metrics import f1_score

y_true = ["HI"] * (62+27+5+6) +\
        ["ID"] * (55+13+13+9+9) +\
        ["IN"] * (7+2+60+2+14+9+6) +\
        ["IP"] * (2 +13+67+7+8+3) +\
        ["NA"] * (1+3+1+86+5+3)+\
        ["OP"] * (1+2+6+2+13+71+5)
y_pred = ["HI"]*62 + ["IN"] * 27 + ["IP"] * 5 + ["HYB"] * 6+\
        ["ID"] * 55 + ["IN"] * 13 + ["NA"] * 13 + ["OP"] * 9 +["HYB"] *9+\
        ["HI"] * 7+["ID"] *2 +["IN"] *60 +["IP"] * 2 +["NA"] *14 +["OP"] *9 +["HYB"] * 6 +\
        ["HI"] * 2 +["IN"] *13 +["IP"] * 67 +["NA"] * 7 +["OP"] *8+["HYB"] * 3 +\
        ["HI"] * 1 +["IN"] * 3 + ["IP"] +["NA"] * 86+["OP"] *5+["HYB"] *3+\
        ["HI"] * 1 +["ID"] * 2 +["IN"] * 6 +["IP"] * 2 +["NA"] * 13 +["OP"] * 71 +["HYB"] *5
labels = "HI,ID,IN,IP,NA,OP,HYB".split(",")

In [2]:
for average in [None, "micro", "macro", "weighted"]:
    print(f"{average=}", end =" ")
    print(f"F1 score: {f1_score(y_true, y_pred, labels=labels, average=average)}")
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_true, y_pred, labels=labels, )
print(cm)

average=None F1 score: [0.71676301 0.69620253 0.54054054 0.75706215 0.74137931 0.7029703
 0.        ]
average='micro' F1 score: 0.6705685618729097
average='macro' F1 score: 0.5935596903190917
average='weighted' F1 score: 0.692398330069187
[[62  0 27  5  0  0  6]
 [ 0 55 13  0 13  9  9]
 [ 7  2 60  2 14  9  6]
 [ 2  0 13 67  7  8  3]
 [ 1  0  3  1 86  5  3]
 [ 1  2  6  2 13 71  5]
 [ 0  0  0  0  0  0  0]]


# Swedish monolingual:

We expect either 0.8261 or 0.8304:

In [3]:
y_true = ["HI"] * (47+15+38) +\
        ["ID"] * (55+7+27+8+3) +\
        ["IN"] * (1+89+3+2+5) +\
        ["IP"] * (4+82+3+3+9) +\
        ["NA"] * (1+2+1+88+1+7)+\
        ["OP"] * (1+7+12+66+14)+\
        ["HYB"] * (4+1+8+20+27+7+33)

HI = ["HI"]
ID = ["ID"]
IN = ["IN"]
IP= ["IP"]
NA= ["NA"]
OP= ["OP"]
HYB= ["HYB"]


y_pred = HI * 47 +IN *15 + HYB * 38 +\
    ID * 55 + IN *7 + NA* 27 +OP *8 + HYB * 3 +\
        ID +IN * 89 + IP*3+NA*2+HYB*5+\
    IN * 4 + IP *82 + NA * 3 + OP * 3 + HYB * 9+\
        ID + IN * 2 + IP + NA * 88 + OP + HYB *7+\
    ID + IP * 7 + NA * 12 + OP * 66 + HYB * 14 + \
        HI * 4 + ID * 1 + IN * 8 + IP * 20 + NA * 27 + OP * 7 + HYB*33
labels = "HI,ID,IN,IP,NA,OP,HYB".split(",")

for average in [None, "micro", "macro", "weighted"]:
    print(f"{average=}", end =" ")
    print(f"F1 score: {f1_score(y_true, y_pred, labels=labels, average=average)}")
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_true, y_pred, labels=labels, )
print(cm)

average=None F1 score: [0.62251656 0.6918239  0.79111111 0.76635514 0.67953668 0.71351351
 0.31578947]
average='micro' F1 score: 0.6562054208273894
average='macro' F1 score: 0.6543780533849844
average='weighted' F1 score: 0.6545377924531753
[[47  0 15  0  0  0 38]
 [ 0 55  7  0 27  8  3]
 [ 0  1 89  3  2  0  5]
 [ 0  0  4 82  3  3  9]
 [ 0  1  2  1 88  1  7]
 [ 0  1  0  7 12 66 14]
 [ 4  1  8 20 27  7 33]]


# Article: Multilingual and Zero-shot is closing in on monolingual web register classification

Figure 3 confusion matrix will be replicated and F1 scores will be calculated on that data.

English master model prediction:

In [20]:
import numpy as np
input_cm = np.array([
[51,1,10,0,2,7,27],
[0,83,5,0,5,6,1],
[1,1,72,1,10,8,8],
[0,0,36,27,8,16,12],
[0,1,5,0,83,6,5],
[1,1,7,0,14,67,10],
[2,1,23,2,34,24,14]
],)


labels = "HI,ID,IN,IP,NA,OP,HYB".split(",")
y_true = []
y_pred = []
for label, num in zip(labels, input_cm.sum(axis=1)):
    y_true.extend([label] * num)
for row in input_cm:
    for label, num in zip(labels, row):
        y_pred.extend([label] * num)


for average in [None, "micro", "macro", "weighted"]:
    print(f"{average=}", end =" ")
    print(f"F1 score: {f1_score(y_true, y_pred, labels=labels, average=average)}")
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_true, y_pred, labels=labels, )
print(cm)

average=None F1 score: [0.66666667 0.88297872 0.55598456 0.41860465 0.6484375  0.57264957
 0.15819209]
average='micro' F1 score: 0.5687679083094556
average='macro' F1 score: 0.5576448228947603
average='weighted' F1 score: 0.5575292587361327
[[51  1 10  0  2  7 27]
 [ 0 83  5  0  5  6  1]
 [ 1  1 72  1 10  8  8]
 [ 0  0 36 27  8 16 12]
 [ 0  1  5  0 83  6  5]
 [ 1  1  7  0 14 67 10]
 [ 2  1 23  2 34 24 14]]


In [23]:
from sklearn.metrics import roc_auc_score

roc_auc = roc_auc_score(y_true, y_pred, labels=labels, multi_class = "ovo")
roc_auc

/home/peterr/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)


TypeError: cannot perform reduce with flexible type